[project]
name = "Rag_Against_The_Machine"
version = "0.9.0"
description = "Simple Retrieval-augmented generation system"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flake8",
    "mypy",
    "fire",
    "bm25s",
    "tqdm",
    "transformers",
    "torch",
    "accelerate",
    "langchain_core",
    "langchain-text-splitters",
    "types-tqdm",
]


[[tool.mypy.overrides]]
module = ["bm25s", "fire"]
ignore_missing_imports = true